# Project Setup

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sqlalchemy

In [2]:
print(sqlalchemy.__version__)

2.0.48

In [3]:
from sqlalchemy import create_engine, inspect
from sqlalchemy import text
from sqlalchemy.schema import CreateSchema
from sqlalchemy import BigInteger, Column, Integer, String, Float, Boolean
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Create SQL Engine and Test Connection

In [4]:
engine = create_engine('postgresql+psycopg2://postgres@localhost/temp_country_club')

In [5]:
with engine.connect() as conn:
    result = conn.execute(text("select count(*) from public.bookings"))
    print(result.fetchone())

(4043,)

In [6]:
bookings = pd.read_sql_table('bookings', con=engine)

In [7]:
facilities = pd.read_sql_table('facilities', con=engine)

In [8]:
members = pd.read_sql_table('members', con=engine)

In [9]:
bookings.head()

   bookid  facid  memid            starttime  slots
0       0      3      1  2012-07-03 11:00:00      2
1       1      4      1  2012-07-03 08:00:00      2
2       2      6      0  2012-07-03 18:00:00      2
3       3      7      1  2012-07-03 19:00:00      2
4       4      8      1  2012-07-03 10:00:00      1

In [ ]:
query = """

"""

In [12]:
revenue = pd.read_sql_query(query, engine)

ProgrammingError: (psycopg2.errors.UndefinedTable) missing FROM-clause entry for table "f"
LINE 1: ...cilities as fleft join bookings as b on b.facid = f.facid le...
                                                             ^

[SQL: with revenue as ( 	select 		b.bookid, 		case 			when b.memid  = 0 then (f.guestcost * b.slots) 			when b.memid != 0 then (f.membercost * b.slots) 		end as session_earning 	from bookings as b 	left join facilities as f on b.facid = f.facid ), run_tot as (select 	f.name as fac_name, 	sum(r.session_earning) as tot_rev from facilities as fleft join bookings as b on b.facid = f.facid left join revenue as r on r.bookid = b.bookid group by f.name order by tot_rev desc) select 	rt.fac_name, 	rt.tot_rev from run_tot as rt where rt.tot_rev < 1000;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [21]:
revenue.head()

   bookid            name  session_earning
0       0    Table Tennis              0.0
1       1  Massage Room 1             19.8
2       2    Squash Court             35.0
3       3   Snooker Table              0.0
4       4      Pool Table              0.0